### ISSUE TITLE
Feature request: mixed casing

### ISSUE THREAD

**Issue by aalemayhu** [egoist/logo-maker#2]
Is there any way you could add support for using mixed casing. For ex. in `JAMstack` would be nice if not all letters were automatically transformed to be uppercased.

Awesome project. ❤️  it!

**Comment by egoist** [comment]
Fow now you can open browser devtools to tweak relevant css, I'm also open to adding an option to toggle this feature.

**Comment by aalemayhu** [comment]
Changing this was easier than I expected, I deployed [my own version](http://logo.alemayhu.de) with the patch below. Thanks.

```diff
diff --git a/src/App.vue b/src/App.vue
index 8419a791de03..db5690feb04e 100644
--- a/src/App.vue
+++ b/src/App.vue
@@ -146,7 +146,6 @@ export default {
       : 'Press Start 2P'
   }";
   font-style: italic;
-  text-transform: uppercase;
   text-shadow: ${this.textShadow};
 }
 </style>`
@@ -243,7 +242,6 @@ a {
 .result {
   font-weight: 700;
   font-style: italic;
-  text-transform: uppercase;
   font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
     'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
     sans-serif;
```

**Comment by egoist** [comment]
So I just solved this in a simple way. (like what you did 😄 https://github.com/egoist/logo-maker/commit/4f6fb63c7cf91bbae27a008f0b1ccfc4911bd543
